# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
query_compiler.py
=================
Reads metric definitions from the API database and compiles them into
warehouse-ready SQL.

Given an entity and its published metrics, produces:
  1. compiled_metric_layer_sql — the assembled CTEs (Metric layer)
  2. compiled_widetable_sql    — the struct SELECT (Widetable layer)

Supports BigQuery, Snowflake, Redshift, DuckDB.

Guided authoring:
  compile_from_expression() takes an entity + a bare SQL expression and generates
  a complete, MESA-compliant metric definition. This is how the product ensures
  core rule compliance by construction — the user never writes FROM clauses,
  raw warehouse paths, or identity column references manually.
"""

from mesa_core.model import Entity, Metric
from mesa_core.model import CompileResult
from mesa_core.compiler.expression_format import format_expression
from mesa_core.compiler.combiner import combiner_model_name, resolve_combiner_default


def compile_entity(entity: Entity, metrics: list[Metric], warehouse: str) -> CompileResult:
    metric_layer_sql = _build_metric_layer(entity, metrics)
    widetable_sql, type_inference_warnings = _build_widetable(entity, metrics, warehouse)

    combiner_sql = ""
    if warehouse == "Snowflake":
        combiner_sql = _build_combiner_snowflake(entity, metrics)

    return CompileResult(
        entity_name=entity.entity_name,
        warehouse=warehouse,
        metric_count=len(metrics),
        compiled_metric_layer_sql=metric_layer_sql,
        compiled_widetable_sql=widetable_sql,
        compiled_combiner_sql=combiner_sql,
        type_inference_warnings=type_inference_warnings,
    )


def _build_metric_layer(entity: Entity, metrics: list[Metric]) -> str:
    """
    Assembles individual metric definitions into a single wide CTE model.
    Output: the compiled {Entity}Metric model (Metric layer).

    Example output:
      -- AUTO-GENERATED by MESA Governance API
      WITH IsSettledStaking AS (
        SELECT StakingEvents.ID AS ID
             , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
        FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
      )
      , EarnPeriod AS (
        ...
      )
      SELECT
        Base.ID
      , IsSettledStaking.IsSettledStaking
      ...
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS Base
      LEFT JOIN IsSettledStaking ON IsSettledStaking.ID = Base.ID
      ...
    """
    header = (
        f"-- AUTO-GENERATED by MESA Governance API — do not edit by hand.\n"
        f"-- Entity: {entity.entity_name} | Source: {entity.source_name}\n"
        f"-- Metrics: {len(metrics)} | Regenerate via POST /v1/metrics/compile\n"
    )

    cte_parts = []
    for metric in metrics:
        indented = "\n".join("  " + line for line in metric.definition_sql.strip().splitlines())
        cte_parts.append(f"{metric.metric_name} AS (\n{indented}\n)")

    with_clause = "WITH " + "\n, ".join(cte_parts)

    select_lines = ["  Base.ID"] + [f"  , {m.metric_name}.{m.metric_name}" for m in metrics]
    select_str = "SELECT\n" + "\n".join(select_lines)

    join_lines = [
        f"LEFT JOIN {m.metric_name}\n  ON {m.metric_name}.ID = Base.ID"
        for m in metrics
    ]
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    from_str = f"FROM {source_ref} AS Base\n" + "\n".join(join_lines)

    return f"{header}\n{with_clause}\n{select_str}\n{from_str}\n"


def _build_widetable(entity: Entity, metrics: list[Metric], warehouse: str) -> tuple[str, list[str]]:
    """
    Generates the Wide Layer (Widetable) SELECT.
    Output: the compiled {Entity} widetable (Widetable layer).

    BigQuery  → SELECT Entity, EntityMetric (STRUCT SELECT — zero maintenance)
    Snowflake → two-OBJECT combiner form: OBJECT_CONSTRUCT(alias.*) x2, ONE
                join to a per-entity combiner model (CAO's decided form —
                SPEC_72; see mesa_core.compiler.combiner)
    Redshift  → SELECT Entity.*, EntityMetric.* (qualified wildcard)
    DuckDB    → SELECT Entity.*, EntityMetric.* (same as Redshift for local dev)

    Returns (sql, type_inference_warnings) — SPEC_72 Slice 4. Snowflake never
    populates type_inference_warnings — the combiner form has no per-metric
    ``::OBJECT(TYPE)`` cast, so there is nothing to infer a type for.
    """
    metric_ref_name = f"{entity.entity_name}Metric"
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    metric_ref = f"{{{{ ref('{metric_ref_name}') }}}}"

    header = (
        f"-- WIDETABLE: {entity.entity_name}\n"
        f"-- Struct-based join of the {entity.entity_name} raw base and all its metrics.\n"
        f"-- No explicit columns. Publish a new metric and recompile — this widetable picks it up automatically.\n"
    )

    if warehouse == "BigQuery":
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {entity.entity_name}\n"
            f"  , {metric_ref_name}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        ), []

    elif warehouse == "Snowflake":
        return _build_widetable_snowflake(entity), []

    else:
        # Redshift / DuckDB — qualified wildcard
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {{{{ dbt_utils.star(ref('{entity.base_table_name}'), relation_alias='{entity.entity_name}') }}}}\n"
            f"  , {{{{ dbt_utils.star(ref('{metric_ref_name}'), relation_alias='{metric_ref_name}') }}}}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        ), []


def _build_widetable_snowflake(entity: Entity) -> str:
    """
    SPEC_72 (combiner architecture) — the Snowflake wide render, byte-matching
    CAO's ``tools/generate_wide_layer.py`` ``build_wide_sql``. TWO qualified-
    wildcard ``OBJECT_CONSTRUCT(alias.*)`` columns — the raw entity and the
    combiner — joined ONCE. No per-metric column list, no per-metric cast; the
    combiner model (``_build_combiner_snowflake``) already did that work.
    """
    entity_var = entity.entity_name  # raw-relation alias
    metrics_var = f"{entity_var}Metrics"  # combiner alias
    combiner_model = combiner_model_name(entity_var)
    join_type = getattr(entity, "wide_join_type", "LEFT") or "LEFT"

    header = (
        f"-- WIDE LAYER: {entity_var} Wide Table (AUTO-GENERATED)\n"
        f"-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.\n"
        f"-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.\n"
        f"-- No explicit column list, no logic, zero maintenance.\n"
        f"-- Regenerate after adding/removing a file in models/metric_layer/{entity_var}_Metrics/:\n"
        f"--   python3 tools/generate_metrics_combiner.py --entity {entity_var}\n"
        f"--   python3 tools/generate_wide_layer.py --entity {entity_var}\n"
        f"-- (run the combiner generator FIRST — the wide layer joins against\n"
        f"-- its output, {combiner_model}, not the individual metric files.)\n"
        f"-- Owner: CI/CD (mechanically generated, do not edit by hand)\n"
        f"--\n"
        f"-- HOW IT WORKS (Snowflake):\n"
        f"--   OBJECT_CONSTRUCT({entity_var}.*) packs the entire row from the {entity_var} alias into a named OBJECT.\n"
        f"--   OBJECT_CONSTRUCT({metrics_var}.*) does the same for the combined metrics alias.\n"
        f"--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.\n"
        f"--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —\n"
        f"--   nothing downstream breaks.\n"
        f"--\n"
        f"--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.\n"
        f"--   Always qualify with the alias: OBJECT_CONSTRUCT({entity_var}.*), OBJECT_CONSTRUCT({metrics_var}.*).\n"
        f"-- Consumer access: {entity_var}Wide.{entity_var}:<Field> / {entity_var}Wide.{metrics_var}:<MetricName> / ...\n"
    )

    body = (
        f"SELECT\n"
        f"    OBJECT_CONSTRUCT({entity_var}.*) AS {entity_var}\n"
        f"    , OBJECT_CONSTRUCT({metrics_var}.*) AS {metrics_var}\n"
        f"FROM {{{{ ref('{entity_var}Raw') }}}} AS {entity_var}\n"
        f"{join_type} JOIN {{{{ ref('{combiner_model}') }}}} AS {metrics_var}\n"
        f"    ON {entity_var}.ID = {metrics_var}.ID\n"
    )

    return header + "\n" + body


def _build_combiner_snowflake(entity: Entity, metrics: list[Metric]) -> str:
    """
    SPEC_72 (combiner architecture) — the per-entity Snowflake metric COMBINER
    model, byte-matching CAO's ``tools/generate_metrics_combiner.py``
    ``build_combiner_sql``. Collapses every metric file for an entity into
    ONE joined, flat-columned model (``<entity_snake>_metrics``) that the wide
    layer then joins to exactly once.
    """
    entity_var = entity.entity_name
    combiner_model = combiner_model_name(entity_var)
    raw_model = f"{entity_var}Raw"

    header = (
        f"-- METRIC COMBINER: {entity_var} Metrics (AUTO-GENERATED)\n"
        f"-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.\n"
        f"-- Regenerate after adding/removing a file in models/metric_layer/{entity_var}_Metrics/:\n"
        f"--   python3 tools/generate_metrics_combiner.py --entity {entity_var}\n"
        f"-- Assembled from every individual metric file in {entity_var}_Metrics/.\n"
        f"-- Contract: 1 row per {raw_model} ID, every metric as a column.\n"
        f"-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills\n"
        f"-- via COALESCE where a safe default exists; otherwise passes NULL\n"
        f"-- through, e.g. survey-average metrics where NULL means 'no response',\n"
        f"-- never a real zero score).\n"
    )

    if not metrics:
        body = (
            f"SELECT\n"
            f"    {entity_var}.ID\n"
            f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}\n"
        )
        return header + "\n" + body

    cte_parts = [
        f"{metric.metric_name} AS (\n    SELECT * FROM {{{{ ref('{metric.metric_name}') }}}}\n)"
        for metric in metrics
    ]
    cte_block = "WITH " + "\n, ".join(cte_parts)

    select_lines = [f"    {entity_var}.ID"]
    for metric in metrics:
        default = resolve_combiner_default(metric.definition_sql)
        if default is None:
            select_lines.append(f"    , {metric.metric_name}.{metric.metric_name}")
        else:
            select_lines.append(
                f"    , COALESCE({metric.metric_name}.{metric.metric_name}, {default}) AS {metric.metric_name}"
            )

    join_lines = [f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}"]
    for metric in metrics:
        join_lines.append(
            f"LEFT JOIN {metric.metric_name}\n"
            f"    ON {entity_var}.ID = {metric.metric_name}.ID"
        )

    body = (
        cte_block + "\n\n"
        + "SELECT\n" + "\n".join(select_lines) + "\n"
        + "\n".join(join_lines) + "\n"
    )
    return header + "\n" + body


def compile_from_expression(
    entity: Entity,
    metric_name: str,
    expression: str,
) -> str:
    """
    Guided authoring: generate a complete, MESA-compliant metric SQL definition
    from just the metric expression (the right-hand side of the AS clause).

    The user provides ONLY the expression. Everything else is generated:
      - FROM clause: canonical dbt source() reference — no raw warehouse paths possible
      - Identity column: entity.identity_column AS identity_column — always present
      - Single output column: one expression = one metric — MESA-CORE-004 by construction

    This function is the structural enforcement of all four MESA core rules.
    When you use guided authoring, you cannot violate them because the violation
    points (raw paths, SELECT *, missing identity, multiple outputs) are never
    in the user's hands.

    Input example:
      entity.entity_name    = "StakingEvents"
      entity.identity_column = "ID"
      entity.source_name    = "anchorage_data_platform"
      entity.base_table_name = "StakingEvents"
      metric_name           = "IsSettledStaking"
      expression            = "UPPER(StakingEvents.RewardState) = 'SETTLED'"

    Output:
      -- GUIDED AUTHORING — generated by MESA Governance API
      -- Entity: StakingEvents | Metric: IsSettledStaking
      -- Expression authored by user. FROM clause, identity column, and source
      -- reference generated by the API. Modifying the generated sections
      -- manually will cause core rule violations on next validation.
      SELECT
        StakingEvents.ID AS ID
        , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
    """
    source_ref = (
        f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    )

    formatted_expr = format_expression(expression)

    return (
        f"-- GUIDED AUTHORING — generated by MESA Governance API\n"
        f"-- Entity: {entity.entity_name} | Metric: {metric_name}\n"
        f"-- Expression authored by user. FROM clause, identity column, and source\n"
        f"-- reference generated by the API. Do not edit the generated sections.\n"
        f"SELECT\n"
        f"  {entity.entity_name}.{entity.identity_column} AS {entity.identity_column}\n"
        f"  , {formatted_expr} AS {metric_name}\n"
        f"FROM {source_ref} AS {entity.entity_name}\n"
    )
