# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
query_compiler.py
=================
Reads metric definitions from the API database and compiles them into
warehouse-ready SQL.

Given an entity and its published metrics, produces:
  1. compiled_metric_layer_sql — the assembled CTEs (Metric layer)
  2. compiled_widetable_sql    — the struct SELECT (Widetable layer)

Supports BigQuery, Snowflake, Redshift, DuckDB.

Guided authoring:
  compile_from_expression() takes an entity + a bare SQL expression and generates
  a complete, MESA-compliant metric definition. This is how the product ensures
  core rule compliance by construction — the user never writes FROM clauses,
  raw warehouse paths, or identity column references manually.
"""

from mesa_core.model import Entity, Metric
from mesa_core.model import CompileResult
from mesa_core.compiler.expression_format import format_expression


def compile_entity(entity: Entity, metrics: list[Metric], warehouse: str) -> CompileResult:
    metric_layer_sql = _build_metric_layer(entity, metrics)
    widetable_sql = _build_widetable(entity, warehouse)
    return CompileResult(
        entity_name=entity.entity_name,
        warehouse=warehouse,
        metric_count=len(metrics),
        compiled_metric_layer_sql=metric_layer_sql,
        compiled_widetable_sql=widetable_sql,
    )


def _build_metric_layer(entity: Entity, metrics: list[Metric]) -> str:
    """
    Assembles individual metric definitions into a single wide CTE model.
    Output: the compiled {Entity}Metric model (Metric layer).

    Example output:
      -- AUTO-GENERATED by MESA Governance API
      WITH IsSettledStaking AS (
        SELECT StakingEvents.ID AS ID
             , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
        FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
      )
      , EarnPeriod AS (
        ...
      )
      SELECT
        Base.ID
      , IsSettledStaking.IsSettledStaking
      ...
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS Base
      LEFT JOIN IsSettledStaking ON IsSettledStaking.ID = Base.ID
      ...
    """
    header = (
        f"-- AUTO-GENERATED by MESA Governance API — do not edit by hand.\n"
        f"-- Entity: {entity.entity_name} | Source: {entity.source_name}\n"
        f"-- Metrics: {len(metrics)} | Regenerate via POST /v1/metrics/compile\n"
    )

    cte_parts = []
    for metric in metrics:
        indented = "\n".join("  " + line for line in metric.definition_sql.strip().splitlines())
        cte_parts.append(f"{metric.metric_name} AS (\n{indented}\n)")

    with_clause = "WITH " + "\n, ".join(cte_parts)

    select_lines = ["  Base.ID"] + [f"  , {m.metric_name}.{m.metric_name}" for m in metrics]
    select_str = "SELECT\n" + "\n".join(select_lines)

    join_lines = [
        f"LEFT JOIN {m.metric_name}\n  ON {m.metric_name}.ID = Base.ID"
        for m in metrics
    ]
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    from_str = f"FROM {source_ref} AS Base\n" + "\n".join(join_lines)

    return f"{header}\n{with_clause}\n{select_str}\n{from_str}\n"


def _build_widetable(entity: Entity, warehouse: str) -> str:
    """
    Generates the Wide Layer (Widetable) SELECT.
    Output: the compiled {Entity} widetable (Widetable layer).

    BigQuery  → SELECT Entity, EntityMetric (STRUCT SELECT — zero maintenance)
    Snowflake → SELECT Entity, EntityMetric (via OBJECT_CONSTRUCT macro)
    Redshift  → SELECT Entity.*, EntityMetric.* (qualified wildcard)
    DuckDB    → SELECT Entity.*, EntityMetric.* (same as Redshift for local dev)
    """
    metric_ref_name = f"{entity.entity_name}Metric"
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    metric_ref = f"{{{{ ref('{metric_ref_name}') }}}}"

    header = (
        f"-- WIDETABLE: {entity.entity_name}\n"
        f"-- Struct-based join of the {entity.entity_name} raw base and all its metrics.\n"
        f"-- No explicit columns. Publish a new metric and recompile — this widetable picks it up automatically.\n"
    )

    if warehouse == "BigQuery":
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {entity.entity_name}\n"
            f"  , {metric_ref_name}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        )

    elif warehouse == "Snowflake":
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {{{{ as_struct('{entity.entity_name}') }}}}\n"
            f"  , {{{{ as_struct('{metric_ref_name}') }}}}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        )

    else:
        # Redshift / DuckDB — qualified wildcard
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {{{{ dbt_utils.star(ref('{entity.base_table_name}'), relation_alias='{entity.entity_name}') }}}}\n"
            f"  , {{{{ dbt_utils.star(ref('{metric_ref_name}'), relation_alias='{metric_ref_name}') }}}}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        )


def compile_from_expression(
    entity: Entity,
    metric_name: str,
    expression: str,
) -> str:
    """
    Guided authoring: generate a complete, MESA-compliant metric SQL definition
    from just the metric expression (the right-hand side of the AS clause).

    The user provides ONLY the expression. Everything else is generated:
      - FROM clause: canonical dbt source() reference — no raw warehouse paths possible
      - Identity column: entity.identity_column AS identity_column — always present
      - Single output column: one expression = one metric — MESA-CORE-004 by construction

    This function is the structural enforcement of all four MESA core rules.
    When you use guided authoring, you cannot violate them because the violation
    points (raw paths, SELECT *, missing identity, multiple outputs) are never
    in the user's hands.

    Input example:
      entity.entity_name    = "StakingEvents"
      entity.identity_column = "ID"
      entity.source_name    = "anchorage_data_platform"
      entity.base_table_name = "StakingEvents"
      metric_name           = "IsSettledStaking"
      expression            = "UPPER(StakingEvents.RewardState) = 'SETTLED'"

    Output:
      -- GUIDED AUTHORING — generated by MESA Governance API
      -- Entity: StakingEvents | Metric: IsSettledStaking
      -- Expression authored by user. FROM clause, identity column, and source
      -- reference generated by the API. Modifying the generated sections
      -- manually will cause core rule violations on next validation.
      SELECT
        StakingEvents.ID AS ID
        , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
    """
    source_ref = (
        f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    )

    formatted_expr = format_expression(expression)

    return (
        f"-- GUIDED AUTHORING — generated by MESA Governance API\n"
        f"-- Entity: {entity.entity_name} | Metric: {metric_name}\n"
        f"-- Expression authored by user. FROM clause, identity column, and source\n"
        f"-- reference generated by the API. Do not edit the generated sections.\n"
        f"SELECT\n"
        f"  {entity.entity_name}.{entity.identity_column} AS {entity.identity_column}\n"
        f"  , {formatted_expr} AS {metric_name}\n"
        f"FROM {source_ref} AS {entity.entity_name}\n"
    )
