# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
query_compiler.py
=================
Reads metric definitions from the API database and compiles them into
warehouse-ready SQL.

Given an entity and its published metrics, produces:
  1. compiled_metric_layer_sql — the assembled CTEs (Metric layer)
  2. compiled_widetable_sql    — the struct SELECT (Widetable layer)

Supports BigQuery, Snowflake, Redshift, DuckDB.

Guided authoring:
  compile_from_expression() takes an entity + a bare SQL expression and generates
  a complete, MESA-compliant metric definition. This is how the product ensures
  core rule compliance by construction — the user never writes FROM clauses,
  raw warehouse paths, or identity column references manually.
"""

from mesa_core.model import Entity, Metric
from mesa_core.model import CompileResult
from mesa_core.compiler.expression_format import format_expression
from mesa_core.compiler.combiner import combiner_model_name, resolve_combiner_default
from mesa_core.compiler.wide_type import resolve_tsql_type
from mesa_core.compiler.wide_columns import (
    build_explicit_object_construct,
    detect_wide_columns,
    has_typed_column,
)

# T-SQL (no native nested type) warehouse strings. Both Synapse Dedicated and
# Azure SQL Database share the flat-typed-CAST wide-layer shape.
_TSQL_WAREHOUSES = ("Synapse", "AzureSQLDatabase")


def compile_entity(entity: Entity, metrics: list[Metric], warehouse: str) -> CompileResult:
    metric_layer_sql = _build_metric_layer(entity, metrics)
    widetable_sql, type_inference_warnings = _build_widetable(entity, metrics, warehouse)

    combiner_sql = ""
    if warehouse == "Snowflake":
        combiner_sql = _build_combiner_snowflake(entity, metrics)
    elif warehouse in _TSQL_WAREHOUSES:
        combiner_sql = _build_combiner_tsql(entity, metrics)
        # SPEC_76 — the T-SQL combiner's flat-column CAST infers a type per
        # metric; surface any metric that fell back to VARCHAR(MAX) so the
        # caller (CLI/Mesantic) can warn — same discipline as Snowflake.
        type_inference_warnings = _tsql_type_warnings(entity, metrics)

    return CompileResult(
        entity_name=entity.entity_name,
        warehouse=warehouse,
        metric_count=len(metrics),
        compiled_metric_layer_sql=metric_layer_sql,
        compiled_widetable_sql=widetable_sql,
        compiled_combiner_sql=combiner_sql,
        type_inference_warnings=type_inference_warnings,
    )


def _build_metric_layer(entity: Entity, metrics: list[Metric]) -> str:
    """
    Assembles individual metric definitions into a single wide CTE model.
    Output: the compiled {Entity}Metric model (Metric layer).

    Example output:
      -- AUTO-GENERATED by MESA Governance API
      WITH IsSettledStaking AS (
        SELECT StakingEvents.ID AS ID
             , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
        FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
      )
      , EarnPeriod AS (
        ...
      )
      SELECT
        Base.ID
      , IsSettledStaking.IsSettledStaking
      ...
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS Base
      LEFT JOIN IsSettledStaking ON IsSettledStaking.ID = Base.ID
      ...
    """
    header = (
        f"-- AUTO-GENERATED by MESA Governance API — do not edit by hand.\n"
        f"-- Entity: {entity.entity_name} | Source: {entity.source_name}\n"
        f"-- Metrics: {len(metrics)} | Regenerate via POST /v1/metrics/compile\n"
    )

    cte_parts = []
    for metric in metrics:
        indented = "\n".join("  " + line for line in metric.definition_sql.strip().splitlines())
        cte_parts.append(f"{metric.metric_name} AS (\n{indented}\n)")

    with_clause = "WITH " + "\n, ".join(cte_parts)

    select_lines = ["  Base.ID"] + [f"  , {m.metric_name}.{m.metric_name}" for m in metrics]
    select_str = "SELECT\n" + "\n".join(select_lines)

    join_lines = [
        f"LEFT JOIN {m.metric_name}\n  ON {m.metric_name}.ID = Base.ID"
        for m in metrics
    ]
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    from_str = f"FROM {source_ref} AS Base\n" + "\n".join(join_lines)

    return f"{header}\n{with_clause}\n{select_str}\n{from_str}\n"


def _build_widetable(entity: Entity, metrics: list[Metric], warehouse: str) -> tuple[str, list[str]]:
    """
    Generates the Wide Layer (Widetable) SELECT.
    Output: the compiled {Entity} widetable (Widetable layer).

    BigQuery  → SELECT Entity, EntityMetric (STRUCT SELECT — zero maintenance)
    Snowflake → two-OBJECT combiner form: OBJECT_CONSTRUCT(alias.*) x2, ONE
                join to a per-entity combiner model (CAO's decided form —
                SPEC_72; see mesa_core.compiler.combiner)
    Synapse / AzureSQLDatabase (T-SQL) → flat-typed combiner form: plain
                flat JOIN of Base.* + the typed metric combiner model (no
                nested type exists on either target) — SPEC_76
    Redshift  → SELECT Entity.*, EntityMetric.* (qualified wildcard)
    DuckDB    → SELECT Entity.*, EntityMetric.* (same as Redshift for local dev)

    Returns (sql, type_inference_warnings) — SPEC_72 Slice 4. Snowflake never
    populates type_inference_warnings — the combiner form has no per-metric
    ``::OBJECT(TYPE)`` cast, so there is nothing to infer a type for. T-SQL
    (Synapse/Azure SQL DB) populates them — the flat-column ``CAST`` type is
    inferred per metric via ``resolve_tsql_type`` (SPEC_76).
    """
    metric_ref_name = f"{entity.entity_name}Metric"
    source_ref = f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    metric_ref = f"{{{{ ref('{metric_ref_name}') }}}}"

    header = (
        f"-- WIDETABLE: {entity.entity_name}\n"
        f"-- Struct-based join of the {entity.entity_name} raw base and all its metrics.\n"
        f"-- No explicit columns. Publish a new metric and recompile — this widetable picks it up automatically.\n"
    )

    if warehouse == "BigQuery":
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {entity.entity_name}\n"
            f"  , {metric_ref_name}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        ), []

    elif warehouse == "Snowflake":
        return _build_widetable_snowflake(entity), []

    elif warehouse in _TSQL_WAREHOUSES:
        return _build_widetable_tsql(entity), []

    else:
        # Redshift / DuckDB — qualified wildcard
        return (
            f"{header}\n"
            f"SELECT\n"
            f"  {{{{ dbt_utils.star(ref('{entity.base_table_name}'), relation_alias='{entity.entity_name}') }}}}\n"
            f"  , {{{{ dbt_utils.star(ref('{metric_ref_name}'), relation_alias='{metric_ref_name}') }}}}\n"
            f"FROM {source_ref} AS {entity.entity_name}\n"
            f"JOIN {metric_ref} AS {metric_ref_name}\n"
            f"  ON {metric_ref_name}.ID = {entity.entity_name}.ID\n"
        ), []


def _build_widetable_snowflake(entity: Entity) -> str:
    """
    SPEC_72 (combiner architecture) — the Snowflake wide render, byte-matching
    CAO's ``tools/generate_wide_layer.py`` ``build_wide_sql``. TWO qualified-
    wildcard ``OBJECT_CONSTRUCT(alias.*)`` columns — the raw entity and the
    combiner — joined ONCE. No per-metric column list, no per-metric cast; the
    combiner model (``_build_combiner_snowflake``) already did that work.

    EXCEPTION (verified against real Farmers PolicyRaw, 2026-09-23): the
    wildcard ``OBJECT_CONSTRUCT({entity_var}.*)`` form CANNOT expand a raw
    column that is itself a typed ``OBJECT(...)``/``ARRAY(OBJECT(...))`` —
    Snowflake raises "Function OBJECT_CONSTRUCT(*) does not support
    OBJECT(...) argument type". Every MESA raw entity following the Raw
    Layer doctrine (quarantined SystemIds OBJECT, quarantined ARRAY detail)
    will eventually have one of these. ``wide_columns.detect_wide_columns``
    parses the raw entity's OWN authored SQL; if it finds any OBJECT/ARRAY-
    typed column, the RAW side switches to the explicit key/value form
    (matching the CustomerAddressWide hand-patch shape, but generated
    instead of hand-maintained). The combiner side is UNCHANGED — the
    combiner model is always flat-typed by construction, never nested.
    """
    entity_var = entity.entity_name  # raw-relation alias
    metrics_var = f"{entity_var}Metrics"  # combiner alias
    combiner_model = combiner_model_name(entity_var)
    join_type = getattr(entity, "wide_join_type", "LEFT") or "LEFT"

    raw_columns = detect_wide_columns(getattr(entity, "definition_sql", "") or "")
    needs_explicit_raw = has_typed_column(raw_columns)

    header_lines = [
        f"-- WIDE LAYER: {entity_var} Wide Table (AUTO-GENERATED)\n",
        f"-- AUTO-GENERATED by tools/generate_wide_layer.py — DO NOT EDIT BY HAND.\n",
    ]
    if needs_explicit_raw:
        header_lines.append(
            f"-- {entity_var}Raw has an OBJECT/ARRAY-typed column — Snowflake's\n"
            f"-- OBJECT_CONSTRUCT({entity_var}.*) wildcard cannot auto-expand a typed\n"
            f"-- nested column, so the {entity_var} side below uses an EXPLICIT\n"
            f"-- key/value OBJECT_CONSTRUCT with ::VARIANT casts on the typed columns.\n"
            f"-- The {metrics_var} combiner side is unaffected (always flat-typed).\n"
        )
    else:
        header_lines.append(
            f"-- Snowflake OBJECT_CONSTRUCT(alias.*) — qualified wildcard, auto-expanding.\n"
            f"-- No explicit column list, no logic, zero maintenance.\n"
        )
    header_lines.append(
        f"-- Regenerate after adding/removing a file in models/metric_layer/{entity_var}_Metrics/:\n"
        f"--   python3 tools/generate_metrics_combiner.py --entity {entity_var}\n"
        f"--   python3 tools/generate_wide_layer.py --entity {entity_var}\n"
        f"-- (run the combiner generator FIRST — the wide layer joins against\n"
        f"-- its output, {combiner_model}, not the individual metric files.)\n"
        f"-- Owner: CI/CD (mechanically generated, do not edit by hand)\n"
        f"--\n"
        f"-- HOW IT WORKS (Snowflake):\n"
        f"--   OBJECT_CONSTRUCT({metrics_var}.*) packs the combined metrics alias into a named OBJECT.\n"
        f"--   The qualified wildcard (alias.*) ensures each OBJECT only contains columns from its own source.\n"
        f"--   Adding a column upstream (a new metric file + combiner regen) expands the OBJECT automatically —\n"
        f"--   nothing downstream breaks.\n"
        f"--\n"
        f"--   NOTE: bare OBJECT_CONSTRUCT(*) after a JOIN is WRONG — it packs ALL joined columns into BOTH objects.\n"
        f"--   Always qualify with the alias.\n"
        f"-- Consumer access: {entity_var}Wide.{entity_var}:<Field> / {entity_var}Wide.{metrics_var}:<MetricName> / ...\n"
    )
    header = "".join(header_lines)

    if needs_explicit_raw:
        raw_select = build_explicit_object_construct(
            entity_var, raw_columns, indent="    ", as_alias=entity_var
        ) + "\n"
    else:
        raw_select = f"    OBJECT_CONSTRUCT({entity_var}.*) AS {entity_var}\n"

    body = (
        f"SELECT\n"
        f"{raw_select}"
        f"    , OBJECT_CONSTRUCT({metrics_var}.*) AS {metrics_var}\n"
        f"FROM {{{{ ref('{entity_var}Raw') }}}} AS {entity_var}\n"
        f"{join_type} JOIN {{{{ ref('{combiner_model}') }}}} AS {metrics_var}\n"
        f"    ON {entity_var}.ID = {metrics_var}.ID\n"
    )

    return header + "\n" + body


def _build_combiner_snowflake(entity: Entity, metrics: list[Metric]) -> str:
    """
    SPEC_72 (combiner architecture) — the per-entity Snowflake metric COMBINER
    model, byte-matching CAO's ``tools/generate_metrics_combiner.py``
    ``build_combiner_sql``. Collapses every metric file for an entity into
    ONE joined, flat-columned model (``<entity_snake>_metrics``) that the wide
    layer then joins to exactly once.
    """
    entity_var = entity.entity_name
    combiner_model = combiner_model_name(entity_var)
    raw_model = f"{entity_var}Raw"

    header = (
        f"-- METRIC COMBINER: {entity_var} Metrics (AUTO-GENERATED)\n"
        f"-- AUTO-GENERATED by tools/generate_metrics_combiner.py — DO NOT EDIT BY HAND.\n"
        f"-- Regenerate after adding/removing a file in models/metric_layer/{entity_var}_Metrics/:\n"
        f"--   python3 tools/generate_metrics_combiner.py --entity {entity_var}\n"
        f"-- Assembled from every individual metric file in {entity_var}_Metrics/.\n"
        f"-- Contract: 1 row per {raw_model} ID, every metric as a column.\n"
        f"-- LEFT JOIN per metric (defensive — a metric missing a row zero-fills\n"
        f"-- via COALESCE where a safe default exists; otherwise passes NULL\n"
        f"-- through, e.g. survey-average metrics where NULL means 'no response',\n"
        f"-- never a real zero score).\n"
    )

    if not metrics:
        body = (
            f"SELECT\n"
            f"    {entity_var}.ID\n"
            f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}\n"
        )
        return header + "\n" + body

    cte_parts = [
        f"{metric.metric_name} AS (\n    SELECT * FROM {{{{ ref('{metric.metric_name}') }}}}\n)"
        for metric in metrics
    ]
    cte_block = "WITH " + "\n, ".join(cte_parts)

    select_lines = [f"    {entity_var}.ID"]
    for metric in metrics:
        default = resolve_combiner_default(metric.definition_sql)
        if default is None:
            select_lines.append(f"    , {metric.metric_name}.{metric.metric_name}")
        else:
            select_lines.append(
                f"    , COALESCE({metric.metric_name}.{metric.metric_name}, {default}) AS {metric.metric_name}"
            )

    join_lines = [f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}"]
    for metric in metrics:
        join_lines.append(
            f"LEFT JOIN {metric.metric_name}\n"
            f"    ON {entity_var}.ID = {metric.metric_name}.ID"
        )

    body = (
        cte_block + "\n\n"
        + "SELECT\n" + "\n".join(select_lines) + "\n"
        + "\n".join(join_lines) + "\n"
    )
    return header + "\n" + body


def _build_widetable_tsql(entity: Entity) -> str:
    """
    SPEC_76 — the T-SQL (Synapse Dedicated + Azure SQL Database) wide render.
    These targets have NO native nested type, so the wide layer is a plain
    flat ``SELECT Base.*, Metrics.*`` join between the raw entity and its
    typed metric combiner model. The typing lives in the combiner (see
    ``_build_combiner_tsql``), not here — this file is pure assembly, exactly
    like the Redshift/DuckDB wildcard form but against the combiner model.
    """
    entity_var = entity.entity_name
    metrics_var = f"{entity_var}Metrics"  # combiner alias
    combiner_model = combiner_model_name(entity_var)
    join_type = getattr(entity, "wide_join_type", "LEFT") or "LEFT"

    header = (
        f"-- WIDE LAYER: {entity_var} Wide Table (AUTO-GENERATED)\n"
        f"-- AUTO-GENERATED by mesa-core — DO NOT EDIT BY HAND.\n"
        f"-- T-SQL (Synapse Dedicated / Azure SQL Database): no native nested\n"
        f"-- type, so this is a FLAT join of the raw columns and the typed\n"
        f"-- metric combiner columns. All typing lives in {combiner_model}.\n"
        f"-- Regenerate after adding/removing a metric file for {entity_var}.\n"
    )

    body = (
        f"SELECT\n"
        f"    {entity_var}.*\n"
        f"    , {metrics_var}.*\n"
        f"FROM {{{{ ref('{entity_var}Raw') }}}} AS {entity_var}\n"
        f"{join_type} JOIN {{{{ ref('{combiner_model}') }}}} AS {metrics_var}\n"
        f"    ON {entity_var}.ID = {metrics_var}.ID\n"
    )

    return header + "\n" + body


def _tsql_type_warnings(entity: Entity, metrics: list[Metric]) -> list[str]:
    """SPEC_76 — warn on any metric whose T-SQL flat-column CAST type was
    inferred (no ``-- WIDE_TYPE_TSQL:`` annotation) so the fallback is never
    silent. Deterministic (metric order preserved)."""
    warnings: list[str] = []
    for metric in metrics:
        tsql_type, was_inferred = resolve_tsql_type(metric.definition_sql)
        if was_inferred:
            warnings.append(
                f"T-SQL type inferred for {entity.entity_name}.{metric.metric_name} "
                f"-> {tsql_type} (no -- WIDE_TYPE_TSQL: annotation). "
                f"Add an annotation to pin the type."
            )
    return warnings


def _tsql_coalesce_default(tsql_type: str) -> str:
    """The T-SQL literal to COALESCE a metric with, matched to its cast type.

    ``COALESCE(x, 0)`` then ``CAST(... AS DECIMAL(18,2))`` is valid T-SQL (0
    promotes to decimal), but we keep the literal shape-consistent with the
    cast so the emitted SQL reads like the ground-truth reference (0 for flag/
    count, 0.0 for money/rate/float).
    """
    upper = tsql_type.upper()
    if upper.startswith("DECIMAL") or upper == "FLOAT":
        return "0.0"
    return "0"


def _build_combiner_tsql(entity: Entity, metrics: list[Metric]) -> str:
    """
    SPEC_76 — the per-entity T-SQL typed metric COMBINER model
    (``<entity_snake>_metrics``), the flat-typed-CAST sibling of the Snowflake
    combiner. Ground truth: SPEC_69a_BUILD / SPEC_69_BUILD_B, the live Azure
    SQL DB + Synapse four-tier builds — every metric becomes ONE typed column
    via ``CAST(COALESCE(m, dflt) AS <tsql_type>) AS m``. Flags → BIT, counts →
    BIGINT, money → DECIMAL(18,2), rates → DECIMAL(8,2), date deltas → INT,
    averages → FLOAT; NULL passes through where a zero-fill would be wrong.
    """
    entity_var = entity.entity_name
    combiner_model = combiner_model_name(entity_var)
    raw_model = f"{entity_var}Raw"

    header = (
        f"-- METRIC COMBINER: {entity_var} Metrics (AUTO-GENERATED)\n"
        f"-- AUTO-GENERATED by mesa-core — DO NOT EDIT BY HAND.\n"
        f"-- T-SQL (Synapse Dedicated / Azure SQL Database): one typed column\n"
        f"-- per metric via CAST(COALESCE(...) AS <type>). Flat modeled because\n"
        f"-- these targets have no nested type. 1 row per {raw_model} ID.\n"
    )

    if not metrics:
        body = (
            f"SELECT\n"
            f"    {entity_var}.ID\n"
            f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}\n"
        )
        return header + "\n" + body

    cte_parts = [
        f"{metric.metric_name} AS (\n    SELECT * FROM {{{{ ref('{metric.metric_name}') }}}}\n)"
        for metric in metrics
    ]
    cte_block = "WITH " + "\n, ".join(cte_parts)

    # Each metric column is emitted as CAST(COALESCE(m.dflt) AS type). The
    # COALESCE default is applied only when the metric has a safe zero-fill
    # (flag/count/money/rate); scores/averages/deltas pass NULL through.
    select_lines = [f"    {entity_var}.ID AS ID"]
    for metric in metrics:
        tsql_type, _inferred = resolve_tsql_type(metric.definition_sql)
        default = resolve_combiner_default(metric.definition_sql)
        if default is None:
            select_lines.append(
                f"    , CAST({metric.metric_name}.{metric.metric_name} AS {tsql_type}) AS {metric.metric_name}"
            )
        else:
            literal = _tsql_coalesce_default(tsql_type)
            select_lines.append(
                f"    , CAST(COALESCE({metric.metric_name}.{metric.metric_name}, {literal}) AS {tsql_type}) AS {metric.metric_name}"
            )

    join_lines = [f"FROM {{{{ ref('{raw_model}') }}}} AS {entity_var}"]
    for metric in metrics:
        join_lines.append(
            f"LEFT JOIN {metric.metric_name}\n"
            f"    ON {entity_var}.ID = {metric.metric_name}.ID"
        )

    body = (
        cte_block + "\n\n"
        + "SELECT\n" + "\n".join(select_lines) + "\n"
        + "\n".join(join_lines) + "\n"
    )
    return header + "\n" + body


def compile_from_expression(
    entity: Entity,
    metric_name: str,
    expression: str,
) -> str:
    """
    Guided authoring: generate a complete, MESA-compliant metric SQL definition
    from just the metric expression (the right-hand side of the AS clause).

    The user provides ONLY the expression. Everything else is generated:
      - FROM clause: canonical dbt source() reference — no raw warehouse paths possible
      - Identity column: entity.identity_column AS identity_column — always present
      - Single output column: one expression = one metric — MESA-CORE-004 by construction

    This function is the structural enforcement of all four MESA core rules.
    When you use guided authoring, you cannot violate them because the violation
    points (raw paths, SELECT *, missing identity, multiple outputs) are never
    in the user's hands.

    Input example:
      entity.entity_name    = "StakingEvents"
      entity.identity_column = "ID"
      entity.source_name    = "anchorage_data_platform"
      entity.base_table_name = "StakingEvents"
      metric_name           = "IsSettledStaking"
      expression            = "UPPER(StakingEvents.RewardState) = 'SETTLED'"

    Output:
      -- GUIDED AUTHORING — generated by MESA Governance API
      -- Entity: StakingEvents | Metric: IsSettledStaking
      -- Expression authored by user. FROM clause, identity column, and source
      -- reference generated by the API. Modifying the generated sections
      -- manually will cause core rule violations on next validation.
      SELECT
        StakingEvents.ID AS ID
        , UPPER(StakingEvents.RewardState) = 'SETTLED' AS IsSettledStaking
      FROM {{ source('anchorage_data_platform', 'StakingEvents') }} AS StakingEvents
    """
    source_ref = (
        f"{{{{ source('{entity.source_name}', '{entity.base_table_name}') }}}}"
    )

    formatted_expr = format_expression(expression)

    return (
        f"-- GUIDED AUTHORING — generated by MESA Governance API\n"
        f"-- Entity: {entity.entity_name} | Metric: {metric_name}\n"
        f"-- Expression authored by user. FROM clause, identity column, and source\n"
        f"-- reference generated by the API. Do not edit the generated sections.\n"
        f"SELECT\n"
        f"  {entity.entity_name}.{entity.identity_column} AS {entity.identity_column}\n"
        f"  , {formatted_expr} AS {metric_name}\n"
        f"FROM {source_ref} AS {entity.entity_name}\n"
    )
