# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
build.py — ``mesa build`` / ``mesa compile`` / ``mesa validate`` logic.

SPEC_66 Slice 4. Pure and deterministic: takes a loaded ``Project`` and writes
compiled four-tier SQL to ``target/``, or validates it in place.

The compile path uses ``mesa_core.compiler.query_compiler.compile_entity`` (the
refit compiler proven parity-identical to the governance repo in Slice 3):

  * Raw layer   — entity.definition_sql verbatim (authored; still carries its
    own {{ source() }} / {{ ref() }} Jinja, which dbt renders downstream).
  * Metric layer — compile_entity's assembled CTE fold.
  * Wide layer  — compile_entity's dialect-aware struct SELECT.
  * View layer  — view.definition_sql verbatim (authored flat SELECT).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from mesa_core.model import Entity, Metric, View
from mesa_core.project import Project


# Placeholder tokens left by ``mesa new entity`` that mean "the user has not
# filled this in yet". Validate surfaces these as findings so a freshly
# scaffolded stub fails loudly instead of silently producing nonsense SQL.
_PLACEHOLDER_RE = re.compile(r"<FILL\s+IN|<source>|<table>", re.IGNORECASE)

# Stamped into every file mesa writes to target/ — makes clear this SQL was
# compiled by mesa-core (MIT) and carries the MESA/Mesantic trademark notice
# even after it's deployed to a warehouse, far from any Python source header.
_GENERATED_BANNER = (
    "-- Generated by mesa-core (MIT License) -- Copyright (c) 2026 Mesantic LLC.\n"
    "-- MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC. mesantic.com\n"
)


def _write_generated(path: Path, sql: str) -> None:
    """Write compiled/copied SQL to ``path`` with the generated-by banner."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_GENERATED_BANNER + (sql or "").rstrip() + "\n")


@dataclass
class Finding:
    """One validation finding (block | warn)."""
    severity: str  # "block" | "warn"
    code: str
    message: str
    location: str = ""


@dataclass
class ValidateResult:
    findings: list[Finding] = field(default_factory=list)

    @property
    def blocking(self) -> list[Finding]:
        return [f for f in self.findings if f.severity == "block"]


def metrics_for_entity(project: Project, entity: Entity) -> list[Metric]:
    return [m for m in project.metrics if m.entity_name == entity.entity_name]


def compile_entity(entity: Entity, metrics: list[Metric], warehouse: str):
    """Thin wrapper over the refit compiler's compile_entity."""
    from mesa_core.compiler.query_compiler import compile_entity as _compile

    return _compile(entity, metrics, warehouse)


# ── Build ────────────────────────────────────────────────────────────────────

def build(project: Project, target_dir: str | Path = "target") -> list[Path]:
    """Compile every entity and write the four tiers to target/.

    ``target_dir`` is resolved by the caller (the CLI passes an absolute path
    rooted at the project directory). Returns the list of files written
    (deterministic order).
    """
    target = Path(target_dir)
    written: list[Path] = []

    # Raw layer — verbatim authored SQL.
    raw_dir = target / "raw_layer"
    for entity in project.entities:
        path = raw_dir / f"{entity.entity_name}Raw.sql"
        _write_generated(path, entity.definition_sql or "")
        written.append(path)

    # Metric + wide layers — compiled.
    metric_dir = target / "metric_layer"
    wide_dir = target / "wide_layer"
    for entity in project.entities:
        metrics = metrics_for_entity(project, entity)
        result = compile_entity(entity, metrics, entity.warehouse)

        mpath = metric_dir / f"{entity.entity_name}Metric.sql"
        _write_generated(mpath, result.compiled_metric_layer_sql)
        written.append(mpath)

        wpath = wide_dir / f"{entity.entity_name}Wide.sql"
        _write_generated(wpath, result.compiled_widetable_sql)
        written.append(wpath)

    # View layer — verbatim authored SQL.
    view_dir = target / "view_layer"
    for view in project.views:
        path = view_dir / f"{view.view_name}.sql"
        _write_generated(path, view.definition_sql or "")
        written.append(path)

    return written


# ── Validate ─────────────────────────────────────────────────────────────────

def validate(project: Project) -> ValidateResult:
    """Run the validation brain over every definition in the project.

    Returns findings; non-empty ``blocking`` means the CLI should exit non-zero.
    """
    from mesa_core.validate.core_rules import validate_metric_sql
    from mesa_core.validate.mesa_verifier import verify_raw_contract

    findings: list[Finding] = []

    # 1. Raw-layer contract + unfilled-placeholder check per entity.
    for entity in project.entities:
        sql = entity.definition_sql or ""
        if _PLACEHOLDER_RE.search(sql):
            findings.append(Finding(
                severity="block",
                code="MESA_RAW_UNFILLED",
                message=(
                    f"Entity '{entity.entity_name}' contains unfilled placeholder "
                    f"tokens (<FILL IN ...> / <source> / <table>). Complete the "
                    f"grain, natural key, and source before building."
                ),
                location=f"{entity.entity_name}Raw.sql",
            ))
        result = verify_raw_contract(sql, identity_column=entity.identity_column)
        for f in result.findings:
            if f.severity == "block":
                findings.append(Finding(
                    severity="block",
                    code=f.code,
                    message=f.message,
                    location=f"{entity.entity_name}Raw.sql",
                ))

    # 2. Core rules per metric.
    for metric in project.metrics:
        for v in validate_metric_sql(metric.definition_sql, metric.entity_name, "ID"):
            findings.append(Finding(
                severity="block",
                code=v.rule_code,
                message=v.error_message,
                location=f"{metric.metric_name}.sql",
            ))

    return ValidateResult(findings=findings)


# ── Format / lint ────────────────────────────────────────────────────────────

def format_project(project: Project, models_dir: str | Path) -> list[str]:
    """Run the MESA formatter over every authored .sql file, rewriting in place.

    Returns the list of file paths rewritten.
    """
    from mesa_core.format.sql_formatter_snowflake import format_snowflake_sql

    rewritten: list[str] = []
    for sql_file in _authored_sql_files(models_dir):
        text = sql_file.read_text()
        formatted, _suggestions = format_snowflake_sql(text, object_name=sql_file.stem)
        if formatted != text:
            sql_file.write_text(formatted)
            rewritten.append(str(sql_file))
    return rewritten


def lint_project(project: Project, models_dir: str | Path) -> list[dict]:
    """Run the formatter in check-mode over every authored .sql file.

    Returns the combined list of lint findings (empty = clean).
    """
    from mesa_core.format.sql_formatter_snowflake import lint_snowflake_sql

    findings: list[dict] = []
    for sql_file in _authored_sql_files(models_dir):
        findings.extend(lint_snowflake_sql(
            sql_file.read_text(),
            file_path=str(sql_file),
        ))
    return findings


def _authored_sql_files(models_dir: str | Path) -> list[Path]:
    """Every authored .sql file (raw / metric / view). wide_layer is generated
    and excluded from formatting — it is machine-assembled, not hand-authored."""
    root = Path(models_dir)
    files: list[Path] = []
    for tier in ("raw_layer", "metric_layer", "view_layer"):
        tier_dir = root / tier
        if tier_dir.is_dir():
            files.extend(sorted(tier_dir.rglob("*.sql")))
    return files
