# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
compiler/targets/dbt.py
========================
DbtEmitter — SPEC_40-A (SPEC_41-A updated)

Turns a governed entity + metrics + optional view into dbt + MetricFlow artifacts.

SPEC_40-A file paths (MetricFlow semantic output):
  models/staging/stg_<entity_snake>.sql         — identity / typed staging model
  models/marts/<entity_snake>__<metric_snake>.sql — one model per metric (ID + value)
  models/marts/<entity_snake>_wide.sql           — LEFT JOIN all metrics (fold invariant)
  models/marts/<entity_snake>_view.sql           — authored view rewritten to ref(wide)
  models/marts/_<entity_snake>.yml               — MetricFlow semantic_models + metrics

SPEC_41-A file paths (gold-standard MESA dbt export — model_zoo_bq shape):
  models/mesa/raw_layer/raw_<entity>.sql         — verbatim authored SQL (hashed ID)
  models/mesa/metric_layer/<Entity>_Metrics/<metric>.sql — 1 metric per file
  models/mesa/metric_layer/<entity>_metrics.sql  — assembler CTE fold
  models/mesa/wide_layer/wide_<entity>.sql       — dialect-aware composite
  models/mesa/view_layer/v_<entity>_*.sql        — BI view over wide
  models/mesa/schema.yml                         — governance projection (SPEC_41-B)

Design guarantees
-----------------
* emit() is PURE and DETERMINISTIC — no git I/O, no network, no DB.
  All side-effectful git writing lives in integrations/definitions/git_writer.py.
* Fold invariant (SPEC_38): the wide model and MetricFlow semantic YAML ALWAYS fold
  ALL metrics. A single-metric redeploy still emits the full wide + full YAML so no
  measures are dropped from the deployed MetricFlow definition.
* The semantic YAML (_<entity>.yml) is the whole point.  A warehouse table alone is
  NOT a MetricFlow metric.  The semantic_models + metrics blocks make the metrics
  queryable via `mf query --metrics <name>`.  Do NOT remove them.
* Non-trivial aggregations (windowed, ratio, complex expressions) emit a
  ``# MESANTIC: manual review — non-trivial aggregation`` comment rather than
  silently mapping to `sum`.  Silent mis-aggregation is a compliance defect.
* CodeConnection is stored but only used for context comments.
  Actual git I/O happens in GitWriter outside this class.

MetricFlow agg-type mapping
-----------------------------
  MESA expression pattern        MetricFlow agg type
  ─────────────────────────────────────────────────────
  SUM(...)                       sum
  COUNT(...)                     count
  COUNT(DISTINCT ...)            count_distinct
  AVG(...)                       average
  MAX(...)                       max
  MIN(...)                       min
  (none of the above)            *comment-flagged* — engineer must review

Wire-label preservation
-----------------------
  Artifact.object_type uses MESA-specific labels for dbt artifacts:
    "dbt_staging"    → staging model
    "dbt_metric"     → one metric model
    "dbt_wide"       → wide model (fold)
    "dbt_view"       → authored view (rewritten)
    "dbt_semantic"   → MetricFlow semantic YAML
  These do NOT overlap with the MESA warehouse tier labels
  ("raw" / "metric" / "widetable" / "view") — they must never be confused.
"""

from __future__ import annotations

import re
import textwrap
from datetime import datetime, timezone

from mesa_core.compiler.targets.base import Artifact


# ── Helpers ────────────────────────────────────────────────────────────────────

def _snake(name: str) -> str:
    """
    Convert PascalCase / mixed-case identifier to snake_case.
    Examples:
        Customer        → customer
        StakingEvents   → staking_events
        TotalRevenue    → total_revenue
    """
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def _generated_header(entity_name: str) -> str:
    """Return the GENERATED-BY comment block for every generated file."""
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"-- GENERATED BY MESANTIC — source of truth is the governed {entity_name} contract.\n"
        f"-- Do not edit by hand; re-run deploy(target=dbt). Rendered {ts}.\n"
    )


def _yaml_generated_header(entity_name: str) -> str:
    """Return the GENERATED-BY comment block for YAML files."""
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# GENERATED BY MESANTIC — source of truth is the governed {entity_name} contract.\n"
        f"# Do not edit by hand; re-run deploy(target=dbt). Rendered {ts}.\n"
    )


def _infer_mf_agg_type(definition_sql: str) -> tuple[str | None, str]:
    """
    Infer the MetricFlow aggregation type and column expression from a MESA metric
    ``definition_sql``.

    Returns
    -------
    (mf_agg, col_expr)

    mf_agg    : MetricFlow aggregation type string, or None when the expression is
                non-trivial and requires manual review.  Callers MUST emit a
                ``# MESANTIC: manual review`` comment instead of a silent fallback.
    col_expr  : The column-level expression to use as the measure ``expr``.
                For aggregated forms this is the inner expression.
                For None (non-trivial) this is the raw definition_sql.

    MetricFlow agg-type vocabulary (dbt-core ≥ 1.6):
        sum, count, count_distinct, average, max, min

    Compliance note
    ---------------
    Non-trivial aggregations (windowed, ratio, arbitrary expressions) MUST NOT be
    silently mapped to ``sum`` — that would produce incorrect governed metrics.
    When mf_agg is None the caller emits a comment flag.  This is the "fail loud"
    contract from SPEC_40 governance caveat #3.
    """
    if not definition_sql:
        # Empty expression: map to count(*) as a safe fallback for entity-level counts.
        return ("count", "*")

    expr = definition_sql.strip()

    # COUNT(DISTINCT ...) → count_distinct
    m = re.match(r"(?i)^COUNT\s*\(\s*DISTINCT\s+(.+?)\s*\)\s*$", expr)
    if m:
        return ("count_distinct", m.group(1).strip())

    # SUM(...) → sum
    m = re.match(r"(?i)^SUM\s*\((.+)\)\s*$", expr)
    if m:
        return ("sum", m.group(1).strip())

    # COUNT(...) → count
    m = re.match(r"(?i)^COUNT\s*\((.+)\)\s*$", expr)
    if m:
        return ("count", m.group(1).strip())

    # AVG(...) → average  (MetricFlow uses "average", not "avg")
    m = re.match(r"(?i)^AVG\s*\((.+)\)\s*$", expr)
    if m:
        return ("average", m.group(1).strip())

    # MAX(...) → max
    m = re.match(r"(?i)^MAX\s*\((.+)\)\s*$", expr)
    if m:
        return ("max", m.group(1).strip())

    # MIN(...) → min
    m = re.match(r"(?i)^MIN\s*\((.+)\)\s*$", expr)
    if m:
        return ("min", m.group(1).strip())

    # Non-trivial expression — cannot safely map to a MetricFlow agg type.
    # Compliance: fail loud, not silent.  Caller emits a manual-review comment.
    return (None, expr)


# ── SQL model builders ────────────────────────────────────────────────────────

def _build_staging_sql(
    entity_name: str,
    identity_col: str,
    header: str,
) -> str:
    """
    Render models/staging/stg_<entity_snake>.sql

    Simple identity-pass-through staging model.  Uses dbt ``{{ source(...) }}``
    macro so dbt knows the lineage back to the raw warehouse source.

    The source name is conventionally ``<entity_snake>_raw`` pointing to the
    MESA raw tier schema; the table is the entity base table.  The customer
    can override source declarations in their own ``sources.yml``.
    """
    entity_snake = _snake(entity_name)
    lines = [
        header,
        f"SELECT",
        f"    {identity_col} AS id,",
        f"    *",
        f"FROM {{{{ source('{entity_snake}_raw', '{entity_name}') }}}}",
    ]
    return "\n".join(lines)


def _build_metric_sql(
    entity_name: str,
    identity_col: str,
    metric_name: str,
    definition_sql: str,
    header: str,
) -> str:
    """
    Render models/marts/<entity_snake>__<metric_snake>.sql

    One model = one metric (ID + computed value).  Groups by ID so the metric
    value is pre-aggregated for the MetricFlow wide join.

    MetricFlow reads the per-metric column value from the wide model; the
    per-metric staging model is a clean building block for the fold.
    """
    entity_snake = _snake(entity_name)
    metric_snake = _snake(metric_name)

    lines = [
        header,
        f"SELECT",
        f"    id,",
        f"    {definition_sql} AS {metric_snake}",
        f"FROM {{{{ ref('stg_{entity_snake}') }}}}",
        f"GROUP BY id",
    ]
    return "\n".join(lines)


def _build_wide_sql(
    entity_name: str,
    identity_col: str,
    all_metrics: list,
    header: str,
) -> str:
    """
    Render models/marts/<entity_snake>_wide.sql

    LEFT JOIN all metric models on id.  This is the MESA fold invariant:
    ALL metrics are always present in the wide model, even during a single-metric
    redeploy.  The wide model is what MetricFlow's semantic_model points at.
    """
    entity_snake = _snake(entity_name)

    if not all_metrics:
        lines = [
            header,
            f"SELECT id",
            f"FROM {{{{ ref('stg_{entity_snake}') }}}}",
        ]
        return "\n".join(lines)

    metric_aliases = [_snake(m.metric_name) for m in all_metrics]

    select_parts = ["base.id"] + [
        f"m{i}.{m_snake}"
        for i, m_snake in enumerate(metric_aliases)
    ]
    select_clause = ",\n    ".join(select_parts)

    join_clauses = "\n".join(
        f"LEFT JOIN {{{{ ref('{entity_snake}__{m_snake}') }}}} m{i}"
        f" ON base.id = m{i}.id"
        for i, m_snake in enumerate(metric_aliases)
    )

    lines = [
        header,
        f"SELECT",
        f"    {select_clause}",
        f"FROM {{{{ ref('stg_{entity_snake}') }}}} base",
        join_clauses,
    ]
    return "\n".join(lines)


def _build_view_sql(
    entity_name: str,
    view_sql: str,
    header: str,
) -> str:
    """
    Render models/marts/<entity_snake>_view.sql

    Rewrites the authored view SQL to reference the wide model via
    ``{{ ref('<entity_snake>_wide') }}`` so dbt tracks the lineage.
    The original SQL is preserved as a comment for audit/review.
    """
    entity_snake = _snake(entity_name)
    lines = [
        header,
        f"-- Original governed view SQL preserved below for audit reference.",
        f"-- The production query sources from the wide model ref to maintain dbt lineage.",
        f"--",
    ]
    # Emit the original SQL as a comment block
    for sql_line in (view_sql or "").strip().splitlines():
        lines.append(f"-- {sql_line}")
    lines += [
        f"",
        f"SELECT *",
        f"FROM {{{{ ref('{entity_snake}_wide') }}}}",
    ]
    return "\n".join(lines)


# ── MetricFlow YAML builder ────────────────────────────────────────────────────

def _build_semantic_yml(
    entity_name: str,
    identity_col: str,
    all_metrics: list,
    time_column: str | None,
    header: str,
) -> str:
    """
    Render models/marts/_<entity_snake>.yml

    Contains MetricFlow ``semantic_models:`` + ``metrics:`` blocks so that
    ``mf query --metrics <name>`` resolves.  This is NOT just a table — it
    is the semantic contract that makes a column a governed MetricFlow metric.

    Structure
    ---------
    semantic_models:
      - name: <entity_snake>
        model: ref('<entity_snake>_wide')
        entities:
          - name: <entity_snake>
            type: primary
            expr: id
        dimensions:
          - name: <identity_snake>
            type: categorical
            expr: id
          [- name: <time_snake>    (if entity has time_column)
             type: time
             type_params:
               time_granularity: day
             expr: <time_column>]
        measures:
          - name: <metric_snake>
            agg: <mf_agg>
            expr: <col_expr>
            # MESANTIC: manual review — non-trivial aggregation  (if agg unmapped)

    metrics:
      - name: <metric_snake>
        type: simple
        type_params:
          measure: <metric_snake>
        label: <metric_name>

    Governance caveat: the ``metrics:`` block is mandatory — without it,
    ``mf query`` cannot resolve the metric even if the measure exists.
    """
    entity_snake = _snake(entity_name)
    id_snake = _snake(identity_col)

    lines: list[str] = [header]

    # ── semantic_models ────────────────────────────────────────────────────
    lines += [
        "semantic_models:",
        f"  - name: {entity_snake}",
        f"    model: ref('{entity_snake}_wide')",
        "",
        "    entities:",
        f"      - name: {entity_snake}",
        f"        type: primary",
        f"        expr: id",
        "",
        "    dimensions:",
        f"      - name: {id_snake}",
        f"        type: categorical",
        f"        expr: id",
    ]

    # Add time dimension if entity has time_column (SPEC_32)
    if time_column:
        time_snake = _snake(time_column)
        lines += [
            f"      - name: {time_snake}",
            f"        type: time",
            f"        type_params:",
            f"          time_granularity: day",
            f"        expr: {time_column}",
        ]

    lines += ["", "    measures:"]

    # One measure per metric
    for metric in all_metrics:
        m_snake = _snake(metric.metric_name)
        definition = (
            getattr(metric, "definition_sql", None)
            or getattr(metric, "sql_definition", "")
            or ""
        )
        mf_agg, col_expr = _infer_mf_agg_type(definition)

        lines.append(f"      - name: {m_snake}")
        if mf_agg is not None:
            lines.append(f"        agg: {mf_agg}")
            lines.append(f"        expr: {col_expr}")
        else:
            # Compliance: non-trivial expression — emit with manual-review flag.
            # NEVER silently map to sum — wrong numbers in a governed metric is a
            # compliance defect (SPEC_40 governance caveat #3).
            lines.append(f"        agg: sum  # MESANTIC: manual review — non-trivial aggregation")
            lines.append(f"        expr: {col_expr}  # original: {definition!r}")

    # ── metrics ────────────────────────────────────────────────────────────
    # One simple metric per measure — makes mf query --metrics <name> work.
    # This block is NOT optional: without it mf cannot resolve the metric.
    lines += ["", "metrics:"]
    for metric in all_metrics:
        m_snake = _snake(metric.metric_name)
        lines += [
            f"  - name: {m_snake}",
            f"    type: simple",
            f"    type_params:",
            f"      measure: {m_snake}",
            f"    label: {metric.metric_name!r}",
        ]

    lines.append("")  # trailing newline
    return "\n".join(lines)


# ── DbtEmitter ────────────────────────────────────────────────────────────────

class DbtEmitter:
    """
    Compile target: dbt models (staging / metric / wide / view SQL) +
    MetricFlow semantic YAML.

    emit() returns kind="file" Artifacts.  All git I/O happens OUTSIDE this
    class in integrations/definitions/git_writer.GitWriter.

    Fold invariant
    --------------
    Even if metric_names is supplied (SPEC_38 single-metric redeploy), this
    emitter ALWAYS emits the FULL wide model + FULL MetricFlow semantic YAML —
    all measures included.  Partial wide models would silently drop measures
    from the deployed MetricFlow definition, breaking ``mf query``.
    The metric_names list is reflected in the PR description (via the
    health_issues metadata channel) so the GitWriter can annotate the PR body.

    Semantic YAML is mandatory
    --------------------------
    The _<entity>.yml semantic_models + metrics block is what makes a column
    a real MetricFlow metric (``mf query --metrics <name>`` works).  A future
    engineer MUST NOT remove it to "simplify" the emitter — the test gate
    asserting the ``metrics:`` key exists guards this invariant.
    """

    target_name: str = "dbt"

    def __init__(self, *, code_connection: object | None = None) -> None:
        """
        Parameters
        ----------
        code_connection : optional context object (Mesantic passes a CodeConnection
            ORM row; MESA Core passes None). Stored for parity but never read —
            this emitter is pure and produces the same Artifacts either way.
        """
        self._cc = code_connection

    # ------------------------------------------------------------------
    # TargetEmitter protocol implementation
    # ------------------------------------------------------------------

    def emit(
        self,
        entity,
        metrics,
        view,
        *,
        layers: list[str] | None = None,
        metric_names: list[str] | None = None,
        location_overrides: dict | None = None,
    ) -> list[Artifact]:
        """
        Generate dbt + MetricFlow Artifacts for the governed contract.

        Parameters
        ----------
        entity       : Entity ORM instance.
        metrics      : list[Metric] ORM instances for this entity.
        view         : Optional View ORM instance (published, authored view).
        layers       : Ignored for dbt target — all tiers always emitted.
        metric_names : SPEC_38 single-metric redeploy signal.
                       Carry-through only: the FULL wide + semantic YAML is
                       always emitted (fold invariant). The metric_names list
                       is recorded in Artifact.health_issues as a special
                       "redeployed_metrics:" marker so the GitWriter can
                       annotate the PR description. health_issues is [] (no
                       actual issues) for a healthy dbt artifact.
        location_overrides : Ignored for dbt target (repo paths are fixed).

        Returns
        -------
        list[Artifact] where every Artifact has kind="file".
        """
        entity_name: str = entity.entity_name
        identity_col: str = entity.identity_column
        time_col: str | None = getattr(entity, "time_column", None)
        entity_snake = _snake(entity_name)
        all_metrics = list(metrics)

        sql_header = _generated_header(entity_name)
        yml_header = _yaml_generated_header(entity_name)

        artifacts: list[Artifact] = []

        # ── 1. Staging model ──────────────────────────────────────────────
        stg_sql = _build_staging_sql(entity_name, identity_col, sql_header)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_staging",
            name=f"stg_{entity_snake}",
            path=f"models/staging/stg_{entity_snake}.sql",
            body=stg_sql,
            health_issues=[],
        ))

        # ── 2. Per-metric models ──────────────────────────────────────────
        for metric in all_metrics:
            m_snake = _snake(metric.metric_name)
            definition = (
                getattr(metric, "definition_sql", None)
                or getattr(metric, "sql_definition", "")
                or ""
            )
            metric_sql = _build_metric_sql(
                entity_name, identity_col, metric.metric_name, definition, sql_header
            )
            artifacts.append(Artifact(
                kind="file",
                object_type="dbt_metric",
                name=f"{entity_snake}__{m_snake}",
                path=f"models/marts/{entity_snake}__{m_snake}.sql",
                body=metric_sql,
                health_issues=[],
            ))

        # ── 3. Wide model (fold invariant — ALL metrics always included) ──
        # The health_issues field carries a "redeployed_metrics:<list>" marker when
        # metric_names is set. The GitWriter reads this to annotate the PR body.
        # It is NOT a blockable health issue — the health gate ignores "redeployed_metrics:" entries.
        wide_health: list[str] = []
        if metric_names:
            wide_health = [f"redeployed_metrics:{','.join(metric_names)}"]

        wide_sql = _build_wide_sql(entity_name, identity_col, all_metrics, sql_header)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_wide",
            name=f"{entity_snake}_wide",
            path=f"models/marts/{entity_snake}_wide.sql",
            body=wide_sql,
            health_issues=wide_health,
        ))

        # ── 4. View model (only when a published view exists) ─────────────
        if view is not None:
            view_sql_raw = getattr(view, "select_sql", None) or ""
            view_sql = _build_view_sql(entity_name, view_sql_raw, sql_header)
            artifacts.append(Artifact(
                kind="file",
                object_type="dbt_view",
                name=f"{entity_snake}_view",
                path=f"models/marts/{entity_snake}_view.sql",
                body=view_sql,
                health_issues=[],
            ))

        # ── 5. MetricFlow semantic YAML (mandatory — the whole point) ─────
        # WITHOUT this block, `mf query --metrics <name>` cannot resolve the metric.
        # This is a table + REAL MetricFlow metric, not just a staging table.
        sem_yml = _build_semantic_yml(
            entity_name, identity_col, all_metrics, time_col, yml_header
        )
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_semantic",
            name=f"_{entity_snake}_semantic",
            path=f"models/marts/_{entity_snake}.yml",
            body=sem_yml,
            health_issues=[],
        ))

        return artifacts


# ── MesaDbtEmitter — SPEC_41-A: gold-standard model_zoo_bq layout ─────────────

class MesaDbtEmitter:
    """
    Compile target: dbt models in the MESA gold-standard layout.

    SPEC_41-A upgrade over DbtEmitter (SPEC_40):
    * Emits real raw-layer model (verbatim authored definition_sql or hashed fallback).
    * Per-metric models reference {{ ref('raw_<entity>') }} not {{ source() }}.
    * Assembler model folds all non-dependent metrics into one CTE model.
    * Wide model is dialect-aware (BigQuery STRUCT / Snowflake OBJECT_CONSTRUCT /
      Redshift dbt_utils.star()).
    * SPEC_41-B: also emits schema.yml with governance metadata + dbt column tests.

    File paths produced (under models/mesa/):
      raw_layer/raw_<entity>.sql
      metric_layer/<Entity>_Metrics/<entity_snake>_<metric_snake>.sql
      metric_layer/<entity_snake>_metrics.sql
      wide_layer/wide_<entity>.sql
      view_layer/v_<entity_snake>_bi.sql          (when view present)
      schema.yml                                   (governance projection)

    Fold invariant
    --------------
    Even when metric_names is supplied (single-metric redeploy), the assembler,
    wide model, and schema.yml ALWAYS include ALL metrics.

    Dialect
    -------
    The wide model is dialect-specific.  Pass dialect="bigquery"|"snowflake"|
    "redshift" to __init__; default is "bigquery".
    """

    target_name: str = "dbt"

    def __init__(
        self,
        *,
        code_connection: object | None = None,
        dialect: str = "bigquery",
    ) -> None:
        self._cc = code_connection
        self._dialect = dialect

    def emit(
        self,
        entity,
        metrics,
        view,
        *,
        layers: list[str] | None = None,
        metric_names: list[str] | None = None,
        location_overrides: dict | None = None,
    ) -> list["Artifact"]:
        """
        Generate SPEC_41 dbt Artifacts for the governed contract.

        Returns
        -------
        list[Artifact] — all kind="file".
        """
        from mesa_core.compiler.targets.dbt_render import (
            build_raw_model,
            build_metric_model,
            build_assembler_model,
            build_wide_model,
            build_view_model,
            _snake,
        )
        from mesa_core.compiler.targets.dbt_schema import build_schema_yml

        entity_name: str = entity.entity_name
        entity_snake = _snake(entity_name)
        all_metrics = list(metrics)

        artifacts: list[Artifact] = []

        # ── 1. Raw-layer model ────────────────────────────────────────────
        raw_sql = build_raw_model(entity)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_raw",
            name=f"raw_{entity_snake}",
            path=f"models/mesa/raw_layer/raw_{entity_snake}.sql",
            body=raw_sql,
            health_issues=[],
        ))

        # ── 2. Per-metric models ──────────────────────────────────────────
        for metric in all_metrics:
            m_snake = _snake(metric.metric_name)
            metric_sql = build_metric_model(entity, metric)
            artifacts.append(Artifact(
                kind="file",
                object_type="dbt_metric",
                name=f"{entity_snake}_{m_snake}",
                path=f"models/mesa/metric_layer/{entity_name}_Metrics/{entity_snake}_{m_snake}.sql",
                body=metric_sql,
                health_issues=[],
            ))

        # ── 3. Assembler model (fold invariant — all non-dependent metrics) ─
        wide_health: list[str] = []
        if metric_names:
            wide_health = [f"redeployed_metrics:{','.join(metric_names)}"]

        assembler_sql = build_assembler_model(entity, all_metrics)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_assembler",
            name=f"{entity_snake}_metrics",
            path=f"models/mesa/metric_layer/{entity_snake}_metrics.sql",
            body=assembler_sql,
            health_issues=wide_health,
        ))

        # ── 4. Wide model (dialect-aware) ─────────────────────────────────
        wide_sql = build_wide_model(entity, self._dialect)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_wide",
            name=f"wide_{entity_snake}",
            path=f"models/mesa/wide_layer/wide_{entity_snake}.sql",
            body=wide_sql,
            health_issues=[],
        ))

        # ── 5. View model (only when a published view exists) ─────────────
        if view is not None:
            view_sql = build_view_model(entity, view)
            view_name_raw = getattr(view, "view_name", f"v_{entity_snake}_bi") or f"v_{entity_snake}_bi"
            view_file_snake = _snake(view_name_raw)
            if not view_file_snake.startswith("v_"):
                view_file_snake = f"v_{view_file_snake}"
            artifacts.append(Artifact(
                kind="file",
                object_type="dbt_view",
                name=view_file_snake,
                path=f"models/mesa/view_layer/{view_file_snake}.sql",
                body=view_sql,
                health_issues=[],
            ))

        # ── 6. schema.yml (SPEC_41-B governance projection) ───────────────
        schema_items = [{"entity": entity, "metrics": all_metrics, "view": view}]
        schema_yml = build_schema_yml(schema_items)
        artifacts.append(Artifact(
            kind="file",
            object_type="dbt_schema",
            name="schema",
            path="models/mesa/schema.yml",
            body=schema_yml,
            health_issues=[],
        ))

        return artifacts
