# ------------------------------------------------------------------------
# mesa-core (c) 2026 Mesantic LLC. MIT License (see LICENSE).
# MESA(tm) and Mesantic(tm) are trademarks of Mesantic LLC.
# ------------------------------------------------------------------------
"""
compiler/targets/dbt_schema.py
================================
SPEC_41-B — MESA dbt schema.yml builder (governance projection).

This module is PURE — no I/O.  It takes governed entity/metric data and
returns a YAML string that can be written as models/mesa/schema.yml.

Governance contract
-------------------
The schema.yml is a READ-ONLY projection of the governed contract.  The DB row
(Entity.owner_team, Entity.sensitivity_level) is the authoritative source of
truth.  schema.yml is a rendered, drift-checked downstream artifact — CI diffs
it against the governed contract; a manually edited schema.yml does NOT update
the governing row.

schema.yml carries two governance fields beyond the model_zoo reference:
  meta.owner        (== Entity.owner_team)
  meta.sensitivity  (== Entity.sensitivity_level)   ← governance win over zoo

Column tests on the raw ID:
  - unique
  - not_null

Output shape matches model_zoo_bq/models/mesa/schema.yml.
Deterministic key ordering → stable diff for CI drift-check.

Compliance note
---------------
schema.yml is the artifact that makes governed metadata visible to the dbt test
runner.  Losing it removes the ``dbt test`` gate on ID uniqueness and nullness —
a compliance regression.  The test gate (test_spec41_schema_yml.py) guards this.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone


# ── Helpers ────────────────────────────────────────────────────────────────────

def _snake(name: str) -> str:
    """PascalCase / mixed-case → snake_case."""
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def _yaml_str(value: str) -> str:
    """Wrap a string value in double-quotes for YAML, escaping inner quotes."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _generated_header() -> str:
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# GENERATED BY MESANTIC — source of truth is the governed contract.\n"
        f"# Do not edit by hand; re-run deploy(target=dbt). Rendered {ts}.\n"
        f"# CI drift-check: diff this file against the governed contract to detect\n"
        f"# unauthorised edits. schema.yml is NOT authoritative — the DB row is.\n"
    )


# ── Schema builder ────────────────────────────────────────────────────────────

def build_schema_yml(entities_with_metrics_and_views: list[dict]) -> str:
    """
    Produce the dbt schema.yml YAML string.

    Parameters
    ----------
    entities_with_metrics_and_views : list of dicts, each with:
        entity  : Entity ORM instance
        metrics : list[Metric] ORM instances
        view    : Optional View ORM instance (first published view, or None)

    Returns
    -------
    str — complete schema.yml content ready to write to disk.

    Output structure (per entity)
    ------------------------------
    models:
      - name: raw_<entity>
        description: "MESA Raw Layer - <Entity> Entity. ..."
        meta:
          layer: "raw"
          entity_type: "<entity_snake>"
          owner: "<owner_team>"
          sensitivity: "<sensitivity_level>"
        columns:
          - name: ID
            description: "Stable, hashed <entity> identifier. Primary key."
            tests: [unique, not_null]
          [- additional typed columns when discoverable]

      - name: <entity>_metrics
        description: "MESA Metric Layer — <Entity> assembled metrics."
        meta: { layer: "metric", entity_type: ..., owner: ... }

      - name: wide_<entity>
        description: "MESA Wide Layer — <Entity> composite wide table."
        meta: { layer: "wide", entity_type: ..., owner: "ci/cd" }

      - name: v_<entity>_bi   (only when view exists)
        description: "MESA View Layer — BI view over <Entity> wide table."
        meta: { layer: "view", entity_type: ..., owner: <view_owner or entity_owner> }

    Key ordering is deterministic (alphabetical within meta/columns blocks).
    """
    lines: list[str] = [_generated_header(), "version: 2", "", "models:"]

    for item in entities_with_metrics_and_views:
        entity = item["entity"]
        metrics = item.get("metrics", [])
        view = item.get("view", None)

        entity_name = entity.entity_name
        entity_snake = _snake(entity_name)
        owner = getattr(entity, "owner_team", "@platform-team") or "@platform-team"
        sensitivity = getattr(entity, "sensitivity_level", "standard") or "standard"

        # ── 1. Raw layer ──────────────────────────────────────────────────────
        lines += [
            f"  # {'=' * 74}",
            f"  # {entity_name} — MESA Layers",
            f"  # {'=' * 74}",
            f"  - name: raw_{entity_snake}",
            f"    description: {_yaml_str(f'MESA Raw Layer - {entity_name} Entity. Establishes canonical {entity_snake} identity with hashed ID.')}",
            f"    meta:",
            f"      layer: {_yaml_str('raw')}",
            f"      entity_type: {_yaml_str(entity_snake)}",
            f"      owner: {_yaml_str(owner)}",
            f"      sensitivity: {_yaml_str(sensitivity)}",
            f"    columns:",
            f"      - name: ID",
            f"        description: {_yaml_str(f'Stable, hashed {entity_snake} identifier (TO_BASE64(SHA256) — base64 STRING). Primary key.')}",
            f"        tests:",
            f"          - unique",
            f"          - not_null",
        ]

        # ── 2. Metric layer (assembler model) ─────────────────────────────────
        if metrics:
            lines += [
                f"",
                f"  - name: {entity_snake}_metrics",
                f"    description: {_yaml_str(f'MESA Metric Layer - {entity_name} assembled metrics. One row per ID, one column per governed metric.')}",
                f"    meta:",
                f"      layer: {_yaml_str('metric')}",
                f"      entity_type: {_yaml_str(entity_snake)}",
                f"      owner: {_yaml_str(owner)}",
                f"      sensitivity: {_yaml_str(sensitivity)}",
                f"    columns:",
                f"      - name: ID",
                f"        description: {_yaml_str(f'Hashed {entity_snake} ID — foreign key to raw_{entity_snake}.')}",
                f"        tests:",
                f"          - not_null",
            ]
            for m in metrics:
                m_snake = _snake(m.metric_name)
                m_desc = getattr(m, "description", "") or m.metric_name
                m_sens = getattr(m, "sensitivity_level", sensitivity) or sensitivity
                lines += [
                    f"      - name: {m_snake}",
                    f"        description: {_yaml_str(m_desc)}",
                ]
                # Flag elevated sensitivity on metric columns
                if m_sens and m_sens != "standard":
                    lines.append(f"        # sensitivity: {m_sens}")

        # ── 3. Wide layer ─────────────────────────────────────────────────────
        lines += [
            f"",
            f"  - name: wide_{entity_snake}",
            f"    description: {_yaml_str(f'MESA Wide Layer - {entity_name} composite wide table. Auto-assembled from raw and metric layers — do not edit columns manually.')}",
            f"    meta:",
            f"      layer: {_yaml_str('wide')}",
            f"      entity_type: {_yaml_str(entity_snake)}",
            f"      owner: {_yaml_str('ci/cd')}",
            f"      sensitivity: {_yaml_str(sensitivity)}",
        ]

        # ── 4. View layer (only when view exists) ─────────────────────────────
        if view is not None:
            view_name_raw = getattr(view, "view_name", f"v_{entity_snake}_bi") or f"v_{entity_snake}_bi"
            # Normalise view file name: snake_case, ensure v_ prefix
            view_snake = _snake(view_name_raw)
            if not view_snake.startswith("v_"):
                view_snake = f"v_{view_snake}"
            view_owner = (
                getattr(view, "owner_id", None)
                or getattr(view, "owner_team", None)
                or owner
            )
            lines += [
                f"",
                f"  - name: {view_snake}",
                f"    description: {_yaml_str(f'MESA View Layer - {entity_name} BI view. Flat SELECT over wide_{entity_snake} for BI tool consumption.')}",
                f"    meta:",
                f"      layer: {_yaml_str('view')}",
                f"      entity_type: {_yaml_str(entity_snake)}",
                f"      owner: {_yaml_str(str(view_owner))}",
                f"      sensitivity: {_yaml_str(sensitivity)}",
            ]

        lines.append("")  # blank line between entities

    return "\n".join(lines) + "\n"
